eureka:
  client:
    fetch-registry: false
server:
  port: 8222
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUCT-SERVICE
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/products/**
        - id: ORDER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/orders/**
        - id: STOCK-SERVICE
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/stocks/**
        - id: USER-SERVICE
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/users/**
        - id: IDENTITY-SERVICE
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/auth/**